# Generated by Django 5.0.1 on 2024-01-20 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "address",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("beds", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "1"), ("not available", "2")],
                        max_length=15,
                    ),
                ),
                ("price_per_night", models.IntegerField()),
                ("available_from", models.DateField()),
                ("available_to", models.DateField()),
                (
                    "picture1",
                    models.ImageField(
                        blank=True, null=True, upload_to="your_upload_path/"
                    ),
                ),
                (
                    "picture2",
                    models.ImageField(
                        blank=True, null=True, upload_to="your_upload_path/"
                    ),
                ),
                (
                    "picture3",
                    models.ImageField(
                        blank=True, null=True, upload_to="your_upload_path/"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservo.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("surname", models.CharField(max_length=30)),
                ("mail", models.EmailField(max_length=254)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reservo.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
