# Generated by Django 5.0.1 on 2024-01-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="name",
            field=models.CharField(default="Name", max_length=20),
        ),
    ]
